name: Cargo.toml Change Monitor

on:
  push:
    branches: [main]
    paths:
      - '**/Cargo.toml'

jobs:
  consolidate-cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed Cargo files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/Cargo.toml
          separator: ','
          
      - name: Create consolidated manifest
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          mkdir -p consolidated
          CONSOLIDATED_FILE="consolidated/cargo_manifests_$(date +%s).txt"
          
          echo "# Consolidated Cargo.toml Files" > $CONSOLIDATED_FILE
          echo "## Changed at: $(date -u)" >> $CONSOLIDATED_FILE
          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo -e "\n\n=== $file ===" >> $CONSOLIDATED_FILE
            cat "$file" >> $CONSOLIDATED_FILE
          done
          
          echo "CONSOLIDATED_FILE=$CONSOLIDATED_FILE" >> $GITHUB_ENV

      - name: Archive consolidated file
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          tar czvf consolidated-manifests.tar.gz -C consolidated .

      - name: Upload artifact
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: consolidated-cargo-manifests
          path: |
            consolidated-manifests.tar.gz
          retention-days: 7
